controllers:
    resource:
        path: ../src/Presentation/Http/Api/Action
        namespace: App\Presentation\Http\Api\Action
    type: attribute

# config/routes.yaml
api_login_check:
    path: /api/login_check
