services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Bdd\:
        resource: '../tests/Bdd/*'

    App\Tests\Bdd\Context\DemoContext:
        arguments:
            - '@App\Kernel'
