services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Bdd\:
        resource: '../tests/Bdd/*'

    App\Tests\Bdd\Context\DemoContext:
        arguments:
            - '@App\Kernel'


#    for uit tests (without api auth)
#    App\Domain\Repository\UserRepositoryInterface:
#        class: App\Tests\__Mock__\InMemoryUserRepository
