# Development environment override
services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./backend/:/app
      - ./.docker/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./.docker/frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true

  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
