name: CI

on:
  push:
    branches:
      - main
      - feature/*
      - fix/*

  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Clean previous stages
        run: make down
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build Docker images
        uses: docker/bake-action@v4
        with:
          pull: true
          load: true
          files: |
            compose.yaml
            compose.override.yaml

  check-services:
    name: Check services
    runs-on: self-hosted
    needs: build
    steps:
      -
        name: Remove previous docker containers
        run: make down
      -
        name: Start services
        run: docker compose up --wait --no-build

      - name: Validate composer.json and composer.lock
        run: docker compose exec -T php composer validate

      -
        name: Check HTTP reachability
        run: curl -v --fail-with-body http://localhost
      -
        name: Check HTTPS reachability
        run: curl -vk --fail-with-body https://localhost/time
      -
        name: Create test database
        run: |
          docker compose exec -T php bin/console -e test doctrine:database:drop --force || true
          docker compose exec -T php bin/console -e test doctrine:database:create
      -
        name: Run migrations
        run: docker compose exec -T php bin/console -e test doctrine:migrations:migrate --no-interaction
      -
        name: Validate migrations
        run: |
          DIFF_OUTPUT=$(docker compose exec php bin/console d:s:u --dump-sql)
          if [ $DIFF_STATUS -eq 0 ]; then
            echo "Schema is sync with entity mappings."
          else
              echo "WARNING: Schema is not in sync with your entity mappings!"
              if [[ ! -z "$DIFF_OUTPUT" ]]; then
                echo "Schema Diff:"
                echo "$DIFF_OUTPUT"
              else
                echo "**Unable to retrieve detailed schema diff. Please refer to Doctrine documentation for alternative methods.**"
              fi
          fi

  code-style:
    name: Check code-style
    runs-on: self-hosted
    needs: check-services
    steps:
      -
        name: Run cs-fixer
        run: docker compose exec -T php vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run

  static-analysis:
    name: Perform static-analysis
    runs-on: self-hosted
    needs: check-services
    steps:
      -
        name: Run phpstan
        run: docker compose exec -T php vendor/bin/phpstan analyze --xdebug --configuration phpstan.dist.neon

  tests:
    name: Run tests
    runs-on: self-hosted
    needs: check-services
    steps:
      -
        name: Run PHPUnit
        run: docker compose exec -T php sh -c "APP_ENV=test ./vendor/bin/phpunit tests"
      -
        name: Run Behat
        run: docker compose exec -T php sh -c "APP_ENV=test ./vendor/bin/behat --colors"

  security:
    name: Symfony Security
    runs-on: ubuntu-latest
    needs: check-services
    steps:
      - uses: actions/checkout@v4
      - uses: symfonycorp/security-checker-action@v5
        with:
          lock: ./backend/composer.lock

  lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
